version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: meroghar-mongo
    environment:
      MONGO_INITDB_DATABASE: meroghar
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    image: node:18
    container_name: meroghar-api
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      MONGODB_URI: mongodb://mongo:27017/meroghar

      NODE_ENV: development

      sessionSecret: "sadfsa22@324GG*&@^"
      saltRounds: "8"

      accessToken: "ss@3%&*HHJJ**"
      refreshToken: "ss@3%&*H%%BBHH&&**"
      accessTokenExpire: "1800s"
      refreshTokenExpire: "7 days"

      dbPassword: "khadkanikan"

      googleClientId: "16273442199-j75mbfaavb22o8am8o2m1ul757uc25l9.apps.googleusercontent.com"
      googleClientSecret: "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"
      facebookClientId: "527744295985309"
      facebookClientSecret: "6744075df1d8ab403a3ce1825bc67513"

      user: "nikantest@zohomail.com"
      pass: "cnodemailerzoho"
      mailSecret: "2342DD##3$$@@)!@)ds"
    ports:
      - "2900:2900"
    depends_on:
      - mongo
    command: sh -c "npm install && npm run dev"

  web:
    image: node:18
    container_name: meroghar-web
    working_dir: /app
    volumes:
      - ./meroghar:/app
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:2900
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev"

volumes:
  mongo_data:
